v1.03|28.08.2026|Nothing update\n -Mods fixed Lichen Farm, and now it's "Frute Farm"
v1.0.2|14.05.2026|THE BIGGEST UPDATE EVER!\n- Premium Script Version\n- Custom key bind on every functions\n- Custom hitbox size\n- Visuals functions\n- AND MORE!
v1.0.1|15.04.2026|Huge Update!\n- Menu & Launch overhaul\n- Key system implemented\n- Hitbox Extender added\n- Premium features: Coming soon
v1.0.0|14.04.2026|Release next gen script for CYP